---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/user/game_events":
    post:
      summary: create game event
      tags:
      - Game Events
      security:
      - JWT: []
      parameters:
      - name: Content-Type
        default: application/json
        in: header
        required: true
      - name: request_body
        in: body
        schema:
          type: object
          properties:
            game_event:
              type: object
              properties:
                type:
                  type: string
                  example: COMPLETED
                  required: true
                occurred_at:
                  type: string
                  example: '2021-10-01 20:00:00'
                  required: true
                game_id:
                  type: string
                  example: c69f13bb-5540-48c2-9e02-d90a0026e4b2
                  required: true
              required: true
      responses:
        '201':
          description: Created
        '422':
          description: Unprocessable Entity
  "/api/games":
    get:
      summary: list games
      tags:
      - Games
      security:
      - JWT: []
      parameters:
      - name: Content-Type
        default: application/json
        in: header
        required: true
      responses:
        '200':
          description: Games returned successfully
  "/api/sessions":
    post:
      summary: create session
      tags:
      - Sessions
      parameters:
      - name: Content-Type
        default: application/json
        in: header
        required: true
      - name: request_body
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
              description: The user email
              example: elevate@example.com
              required: true
            password:
              type: string
              description: The user password
              example: '123456'
              required: true
      responses:
        '201':
          description: Created
        '422':
          description: Unprocessable Entity
  "/api/user":
    post:
      summary: create user
      tags:
      - Users
      parameters:
      - name: Content-Type
        default: application/json
        in: header
        required: true
      - name: request_body
        in: body
        schema:
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                  description: The user email
                  example: elevate@example.com
                  required: true
                password:
                  type: string
                  description: The user password
                  example: '123456'
                  required: true
                password_confirmation:
                  type: string
                  description: The user password confirmation
                  example: '123456'
                  required: true
                username:
                  type: string
                  description: User's username
                  example: username
                  required: true
                full_name:
                  type: string
                  description: User's full name
                  example: John Doe
                  required: true
      responses:
        '201':
          description: Created
        '422':
          description: Unprocessable Entity
    get:
      summary: show user stats
      tags:
      - Users
      security:
      - JWT: []
      parameters:
      - name: Content-Type
        default: application/json
        in: header
        required: true
      responses:
        '200':
          description: OK
        '401':
          description: Unathorized
securityDefinitions:
  JWT:
    description: 'Example: ''Bearer xxx.yyy.zzz'''
    type: apiKey
    name: Authorization
    in: header
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
